### ISSUE TITLE
wait_until_ready not working

### ISSUE THREAD

**Issue by griftnrun** [rackerlabs/terraform-provider-spot#15]
Hi,

Based on the updates yesterday, i tried adding wait_until_ready under the cloudspace resource but facing issues as its not recognized.

terraform plan                                 
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 24, in resource "spot_cloudspace" "prod":
│   24:   wait_until_ready   = true 
│ 
│ An argument named "wait_until_ready" is not expected here.
╵
           
terraform version:
Terraform v1.8.5 on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/rackerlabs/spot v0.0.12

# 3 different of cloudspace resource for prod/staging/dev.
resource "spot_cloudspace" "prod" {
  cloudspace_name    = local.cloudspace_name_prod
  region             = var.region
  hacontrol_plane    = false
  preemption_webhook = var.slack_webhook
  wait_until_ready   = true

**Comment by TheNilesh** [comment]
Fixed in release [0.0.13](https://github.com/rackerlabs/terraform-provider-spot/releases/tag/v0.0.13)
